name: "learning_qa"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "2020:8080"
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/swagger.json
    volumes:
      - swagger.json:/usr/share/nginx/html/swagger.json
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "2021:8080"

volumes:
  swagger.json:
  
